version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    allow:
      - dependency-name: '@distube/ytdl-core'
      - dependency-name: '@distube/ytsr'
