version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
    allow:
      - dependency-name: 'youtube-dl-exec'
      - dependency-name: 'youtubei.js'
      - dependency-name: 'discord.js'
      - dependency-name: '@discordjs/voice'
      - dependency-name: '@discordjs/opus'
