name: Create release

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: write
  discussions: write

jobs:
  release:
    name: GitHub Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: master
          fetch-depth: 0

      - name: Get latest tag
        id: tag
        run: echo "value=$(git describe --tags --abbrev=0)" >> "$GITHUB_OUTPUT"

      - uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          tag_name: ${{ steps.tag.outputs.value }}
          name: ${{ steps.tag.outputs.value }}
